sudo: required
language: cpp
compiler:
  - gcc
# Change this to your needs
script: ./build.sh
deploy:
    provider: releases
    api_key: $KEY
    file: ./.build/FRCUserProgram
    skip_cleanup: true
    on:
        tags: true
        branch: travis
